{% set native = 'm2w64-' if win else '' %}
{% set posix = 'm2-' if win else '' %}
{% set version = "4.1.3" %}

package:
  name: r-base-split
  version: {{ version }}

source:
  - url: https://cran.r-project.org/src/base/R-4/R-{{ version }}.tar.gz
    sha256: 15ff5b333c61094060b2a52e9c1d8ec55cc42dd029e39ca22abdaa909526fed6
    patches:
      - 0001-Darwin-Remove-unicode-elipsis-character-from-grDevic.patch
      - 0002-Fix-trio-config.h-include-depth-issue.patch
      - 0003-Win32-Do-not-link-static-libgcc.patch
      - 0004-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch
      - 0005-Win32-Prevent-conversion-of-R_ARCH-to-abs-Windows-pa.patch
      - 0006-Darwin-Avoid-setting-DYLD_FALLBACK_LIBRARY_PATH.patch
      - 0007-Use-AC_SEARCH_LIBS-to-search-for-ncursesw-then-ncurs.patch
      - 0008-Linux-Do-not-modify-LD_LIBRARY_PATH.patch
      - 0009-javareconf-Do-not-fail-on-compile-fail.patch
      - 0010-Revert-part-of-9b818c6dc00143ff18775a4015a3f43b5196f.patch
      - 0011-javareconf-macOS-Continue-to-allow-system-Java-lt-9-.patch
      - 0012-Allow-rpath-in-tcltk-dylib-LC_LOAD_DYLIB-command.patch
      - 0013-Add-luuid-to-X_PRE_LIBS.patch
      - 0014-link-Xt-to-uuid.patch
      - 0015-Check-for-changes-then-forcibly-mv-in-javareconf.in.patch
      - 0016-Use-LAPACK_LDFLAGS-in-Rlapack_la_LIBADD.patch
  # The following are used for the Mingw_w64 builds, added in
  # https://github.com/conda-archive/conda-recipes/commit/959fa4bb8b14c522e5f791d1463c9bc0021059e0
  - url: http://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/curl-ca-bundle.crt            # [win]
    sha256: 85ccbba308acf67df5e291cc8a8e91d3b9ff8a7ca686de259d68d4d4ab4f14df                 # [win]
    folder: win-extra-files                                                                  # [win]
  - url: http://constexpr.org/innoextract/files/innoextract-1.6/innoextract-1.6-windows.zip  # [win]
    sha256: 33d61133401bb6a919b299f282b5e8f0aada67253460b0c11c85b56cdb1ea0d3                 # [win]
    folder: win-extra-files/innoextract                                                      # [win]
  - url: http://files.jrsoftware.org/is/5/innosetup-5.5.9-unicode.exe                        # [win]
    sha256: 5b51ae6977bebba937ac18e0e80c1899e37dfaa12f51ccd817978ef07ae19cb3                 # [win]
    folder: win-extra-files                                                                  # [win]

build:
  number: 6

outputs:
  - name: r-base
    script: build-r-base.sh  # [not win]
    script: bld-r-base.bat  # [win]
    build:
      merge_build_host: true  # [win]
      rpaths:
        - lib/R/lib/
        - lib/
      no_link:
        # These files are modified by R CMD javareconf and can
        # point to different Java implementations in each env.
        - lib/R/etc/Makeconf
        - lib/R/etc/ldpaths
        - lib/R/etc/javaconf
        - lib/R/etc/x64/Makeconf
        - lib/R/etc/x64/ldpaths
        - lib/R/etc/x64/javaconf
      detect_binary_files_with_prefix: true
    requirements:
      build:
        - gnuconfig  # [unix]
        - {{ compiler('c') }}                # [not win]
        - {{ compiler('cxx') }}              # [not win]
        - {{ compiler('fortran') }}          # [not win]
        - gfortran_impl_{{ build_platform }} {{ fortran_compiler_version }}  # [(build_platform != target_platform) and linux]
        - {{ compiler('m2w64_c') }}          # [win]
        - {{ compiler('m2w64_cxx') }}        # [win]
        - {{ compiler('m2w64_fortran') }}     # [win]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libxrender') }}            # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('libsm-devel') }}           # [linux]
        - {{ cdt('libice-devel') }}          # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxt') }}                 # [linux]
        - {{ cdt('libxt-devel') }}           # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('java-1.7.0-openjdk') }}    # [linux]
        - {{ posix }}pkg-config
        - posix                              # [win]
        - m2-texinfo-tex                     # [win]
        - m2-texinfo                         # [win]
        - m2-p7zip                           # [win]
        - miktex                             # [win]
        #- texlive-core                       # [unix]
        - texinfo                            # [unix]
        - openjdk
        - {{ posix }}autoconf
        - {{ posix }}automake-wrapper        # [win]
        - {{ posix }}automake                # [not win]
        - make                               # [not win]
        - libcurl                            # [not win]
        - freetype                            # [build_platform != target_platform]
        - readline                            # [build_platform != target_platform]
        - ncurses                             # [build_platform != target_platform]
        - libcurl                             # [build_platform != target_platform]
        - xz                                  # [build_platform != target_platform]
        - libpng                              # [build_platform != target_platform]
        - bzip2                               # [build_platform != target_platform]
        - cairo                               # [build_platform != target_platform]
        - libjpeg-turbo                       # [build_platform != target_platform]
        - libiconv                            # [osx and (build_platform != target_platform)]
        - libuuid                             # [linux and (build_platform != target_platform)]
        - glib                                # [unix and (build_platform != target_platform)]
        - bwidget                             # [build_platform != target_platform]
        - tktable                             # [build_platform != target_platform]
        - pango                               # [build_platform != target_platform]
        - icu                                 # [build_platform != target_platform]
        - pcre2                               # [build_platform != target_platform]
        - tk                                  # [build_platform != target_platform]
        - zlib                                # [build_platform != target_platform]
        - gsl                                 # [build_platform != target_platform]
        - libtiff                             # [build_platform != target_platform]
        - libxml2                             # [build_platform != target_platform]
        - libssh2                             # [build_platform != target_platform]
        - krb5                                # [build_platform != target_platform]
        - libblas                             # [build_platform != target_platform]
        - liblapack                           # [build_platform != target_platform]
      host:
        # This is a hack, strong run_exports should cause this to be added
        - llvm-openmp                        # [osx]
        - freetype                           # [not win]
        - readline                           # [not win]
        - ncurses                            # [not win]
        - libcurl                            # [not win]
        - xz                                 # [not win]
        - libpng                             # [not win]
        - bzip2                              # [not win]
        - {{ native }}bzip2                  # [win]
        - cairo                              # [not win]
        - {{ native }}libjpeg-turbo          # [win]
        - libjpeg-turbo                      # [not win]
        - libiconv                           # [osx]
        - {{ native }}libiconv               # [win]
        - libuuid                            # [linux]
        - {{ native }}gmp                    # [win]
        - glib                               # [unix]
        - {{ native }}fftw                   # [win]
        - {{ native }}xz                     # [win]
        - {{ native }}mpfr                   # [win]
        - {{ native }}libsndfile             # [win]
        - {{ native }}bwidget
        - {{ native }}tktable
        - {{ native }}libpng                 # [win]
        - pango                              # [not win]
        - {{ native }}icu                    # [win]
        - icu                                # [not win]
        - pcre2                              # [not win]
        - {{ native }}pcre2                  # [win]
        - tk                                 # [not win]
        - {{ native }}tk                     # [win]
        - {{ native }}zlib                   # [win]
        - zlib                               # [not win]
        - {{ native }}gsl                    # [win]
        - gsl                                # [not win]
        - {{ native }}libtiff                # [win]
        - libtiff                            # [not win]
        - {{ native }}libxml2                # [win]
        - libxml2                            # [not win]
        - libssh2                            # [not win]
        - krb5                               # [not win]
        - libblas
        - liblapack
        # sed is in host env because its path is recorded in R's shell wrapper
        - sed                                # [linux]
      run:
        - _r-mutex 1.* anacondar_1
        # Needed by R CMD javareconf
        - make                               # [not win]
        - gcc_impl_{{ target_platform }}  >={{ c_compiler_version|default("0") }}    # [linux]
        - gxx_impl_{{ target_platform }}  >={{ cxx_compiler_version|default("0") }}  # [linux]
        - gfortran_impl_{{ target_platform }}  # [linux]
        - {{ c_compiler|default("blah") }}_{{ target_platform }} >={{ c_compiler_version|default("0") }}      # [osx]
        - {{ cxx_compiler|default("blah") }}_{{ target_platform }} >={{ cxx_compiler_version|default("0") }}  # [osx]
        - {{ compiler('fortran') }}  # [osx]
        - {{ pin_compatible('llvm-openmp', max_pin=None) }}      # [osx]
        - curl                                 # [not win]
        - {{ native }}bzip2                    # [win]
        - {{ native }}libjpeg-turbo            # [win]
        - {{ native }}libiconv                 # [win]
        - libuuid                              # [linux]
        - xorg-libxt                           # [linux]
        - {{ native }}gmp                      # [win]
        - {{ native }}fftw                     # [win]
        - {{ native }}xz                       # [win]
        - {{ native }}mpfr                     # [win]
        - {{ native }}libsndfile               # [win]
        - {{ native }}bwidget
        - {{ native }}tktable
        - {{ native }}libpng                   # [win]
        - {{ native }}pcre2                    # [win]
        - {{ native }}tk                       # [win]
        - {{ native }}zlib                     # [win]
        - {{ native }}gsl                      # [win]
        - {{ native }}libtiff                  # [win]
        - {{ native }}libxml2                  # [win]
        # Once run_exports are in place these will not be necessary:
        - {{ pin_compatible('pango') }}      # [not win]
        - {{ pin_compatible('bzip2') }}      # [not win]
        - {{ pin_compatible('icu') }}        # [not win]
        - sed                                # [linux]

    test:
      commands:
        - R -h
        - R --version
        - R -e "library('tcltk')"            # [linux]
        - R -e \"library('tcltk')\""         # [win]
        - Rscript --version
        - Rscript -e  'cat("ok\\n")'
        # Report on the optional features compiled into this build of R.
        - R -e "capabilities()"              # [not win]
        - R -e \"capabilities()\""           # [win]
        # Show third-party graphics software available
        - R -e "grSoftVersion()"             # [not win]
        - R -e \"grSoftVersion()\""          # [win]
        # TODO does not work on windows, because winCairo.dll is missing
        - Rscript test-svg.R                 # [not win]
        - open                               # [win]
         # There doesn't seem to be a way to test this one
         # - RSetReg                         # [win]
        - Rfe --help                         # [win]
        - Rterm --help                       # [win]
        - Rterm --version                    # [win]
        # Prevent regression mentioned in https://github.com/conda-forge/r-base-feedstock/issues/50
        - Rscript -e "stopifnot(capabilities('jpeg'), TRUE)"
        - Rscript -e "stopifnot(capabilities('png'), TRUE)"
        - if not exist %PREFIX%\\Lib\\R\\bin\\x64\\R.lib exit 1  # [win]
      files:
        - test-svg.R


  - name: cross-r-base
    build:
      skip: true  # [win]
    script: install-cross-activate.sh
    requirements:
      run:
        - {{ pin_subpackage("r-base", exact=True) }}
        - rsync
    test:
      commands:
        - test -f $PREFIX/etc/conda/activate.d/activate-cross-r-base.sh

about:
  home: http://www.r-project.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: R is a free software environment for statistical computing and graphics.

extra:
  feedstock-name: r-base
  recipe-maintainers:
    - conda-forge/r
    - isuruf
    - mbargull
    - mingwandroid
    - ocefpaf
    - sodre
    - xhochy
