{% set version = '3.4.0' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-base
  version: {{ version }}

source:
  url: https://cran.r-project.org/src/base/R-3/R-{{ version }}.tar.gz
  sha256: 288e9ed42457c47720780433b3d5c3c20983048b789291cc6a7baa11f9428b91
  patches:
    - 0001-Win32-Stop-confusing-PECOFF_SHLIBS-with-CYGWIN_BUILD.patch  # [win]
    - 0002-Win32-Fix-trio-config-h-include-depth-issue.patch  # [win]
    - 0003-Win32-Do-not-static-libgcc-link.patch  # [win]
    - 0007-Win32-MSYS2-ENV_CONV_EXCL_R_ARCH.patch  # [win]

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true
  # No openjdk on win32.
  skip: true  # [win32]

requirements:
  build:
    - posix                    # [win]
    - m2-texinfo-tex           # [win]
    - m2-texinfo               # [win]
    - m2-curl                  # [win]
    - m2-p7zip                 # [win]
    - readline 6.2*            # [not win]
    - ncurses 5.9*             # [not win]
    - gcc                      # [not win]
    - jpeg 9*                  # [not win]
    - curl                     # [not win]
    - automake                 # [not win]
    - openjdk
    - {{native}}pkg-config
    - {{native}}bzip2 1.0.*    # [not osx]
    - {{native}}libjpeg-turbo  # [win]
    - {{native}}toolchain      # [win]
    - {{native}}libiconv       # [win]
    - {{native}}gmp            # [win]
    - {{native}}fftw           # [win]
    - {{native}}xz 5.2.*
    - {{native}}mpfr           # [win]
    - {{native}}libsndfile     # [win]
    - {{native}}bwidget        # [win]
    - {{native}}tktable        # [win]
    - {{native}}pcre
    - {{native}}icu 58.*       # [not win]
    - {{native}}pango 1.40.*   # [not win]
    - {{native}}tk 8.6.*       # [win]
    - {{native}}tk 8.5.*       # [not win]
    # R does not build with zlib 1.2.11
    # See https://github.com/conda-forge/r-base-feedstock/issues/4
    - {{native}}zlib 1.2.8
    - {{native}}gsl
    - {{native}}libpng >=1.6.21,<1.7  # [win]
    - {{native}}libpng >=1.6.28,<1.7  # [not win]
    - {{native}}libtiff 4.0.*
    - {{native}}libxml2 2.9.*
    - miktex  # [win]
  run:
    - m2-texinfo-tex           # [win]
    - m2-texinfo               # [win]
    - m2-curl                  # [win]
    - m2-p7zip                 # [win]
    - readline 6.2*            # [not win]
    - ncurses 5.9*             # [not win]
    - libgcc                   # [not win]
    - jpeg 9*                  # [not win]
    - curl                     # [not win]
    - {{native}}bzip2 1.0.*    # [not osx]
    - {{native}}gcc-libs       # [win]
    - {{native}}libjpeg-turbo  # [win]
    - {{native}}toolchain      # [win]
    - {{native}}libiconv       # [win]
    - {{native}}gmp            # [win]
    - {{native}}fftw           # [win]
    - {{native}}mpfr           # [win]
    - {{native}}libsndfile     # [win]
    - {{native}}bwidget        # [win]
    - {{native}}tktable        # [win]
    - {{native}}icu 58.*       # [not win]
    - {{native}}pango 1.40.*   # [not win]
    - {{native}}tk 8.6.*       # [win]
    - {{native}}tk 8.5.*       # [not win]
    - {{native}}libpng >=1.6.21,<1.7  # [win]
    - {{native}}libpng >=1.6.28,<1.7  # [not win]
    - {{native}}xz 5.2.*
    - {{native}}pcre
    # R does not build with zlib 1.2.11
    # See https://github.com/conda-forge/r-base-feedstock/issues/4
    - {{native}}zlib 1.2.8
    - {{native}}gsl
    - {{native}}libtiff 4.0.*
    - {{native}}libxml2 2.9.*

test:
  requires:
    - openjdk
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'
    - R CMD javareconf  # [unix]
    - open  # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg        # [win]
    - Rfe --help       # [win]
    - Rterm --help     # [win]
    - Rterm --version  # [win]
    # check include files
    - if not exist %PREFIX%\\R\\include\\R.h exit 1    # [win]
    - conda inspect linkages -p $PREFIX r-base  # [not win]
    - conda inspect objects -p $PREFIX r-base  # [osx]

about:
  home: http://www.r-project.org/
  license: GPL-3.0
  license_file: COPYING
  summary: 'R is a free software environment for statistical computing and graphics.'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - ocefpaf
    - sodre
