bot:
  abi_migration_branches:
  - 3.6.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
conda_build:
  pkg_format: '2'
test: native_and_emulated
