travis:
  secure:
    BINSTAR_TOKEN: dFQqBLu0IlhbS3nltEG5GO+8/w64gyzzYntVA9J+lMb/RFNjYpY5CPadug3D+6PNBGSby9bd5xKrJOHZNlfdj8yTAp02BVmW7fGheWQv9CPc2dF2MG2QYRrlYnMh/xt7o1EGf5bwMZEFeRO3HWUtPcPNCDtsG0gfJRiCqtP/z7x1LpKWLYOT6RUALZj5OyJ9VHBH1/iTLnirv6BAkA79bcn1lpt5x91Q1c24YtE0eNeO4dj6l5LuIDm0E8ZdjLZpyU+koP3q465j0FnBqpEPd7ufz/IpNUifB2HLYCS6tfB+lROCyVI1Y6jRRPHpua4BxGSpzuZlqh89WPTAab9aBjgYVpfJ3DiEtoSSsC3G12jG4bjWyQLgeTI0ULE6g95hZHN70/5o6pdolg3IkE0H8URvbGReRihVZrIo75LOHkTYKwpfdHALvKSDuXtgswvwLEmFIbvKnHIPIa2YSvxdNhaVx3d3cqkx4eHT8Ms3g477e4Woua0bbuLxDInBxm9WB0oHx2JPu69Yur75H48wGqS4BaSIk0p5qezAljNuNwlSTyB3Pk+WSkoICFeDVv/JtJhsIFZFavhXGyqKmi1lAeISzled+dE4wzNGxDWPva7jWA5fFCXKC2PBY5ER6UGXcvxfADPnP6nrlc3oiU4tnVrIQ0gjcfMVguk6nAAJoqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
