travis:
  secure:
    BINSTAR_TOKEN: XQdAzbAf41uaBVeNolMIlJYsFYfLCymOm1U7Q2ZAK9L/eyD0/mzHyHmVNLTX11nmMM2TDMWvWllGrECod61qSZ/H8a350uon2QclaiA4HbTGV4RNDtLTWuiHfUw5Gls1ulG1TNPVs3647pgXqxxdic64lUFGzoc8wRqt/V4VBcWraDEJUxoxKADRNjj8aMzXZso6qkZCkJR3KdlUO1PkZCzTuydT9YYzcQ4MyrJBTlP40aLbfiiMNmY6Q4s44EYk7U8oJlmtf2u0wt/hDYUbc/ylF0+1PASU9jEVV8Hm9qbpNrlhoDC29Q76ouBejX13lZQ2CD7B5alJWfO18a1xQP7FG8q+AafEs+DsfFW5It/AAQ2//M2LAXj+/A+YcEbZMInk1tq1B3iORsDu2sljQMyv6KBdoe9fdhTx0ONZBI4G65+Fj68LKnOC9gI+EoMm2VAHawPsKXRkDA43NZNPNnJ0fcs3a/iGsy9m1DkuosrmoJXkzbgdHQ/SN5XJqvpqIk27eeUk82+YEvxOyoDTYalQSwtZhF42M/ZdarZ+vzT96woCEOvED6/m6bPB43WEOm6/eWkDQdpJVmkE0v2g1ZAluzhodM6/esWko8VVIIiEPb/rDRQU1xSE2gv6X6h28GoM40kjsRKQyOpUy9pMfbtZYKXXcBW1IXPkHJFSO9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
