bot:
  abi_migration_branches:
  - 4.1.x
  - 4.2.x
  - 4.3.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: native
  linux_ppc64le: native
test: native_and_emulated
